# Generated by Django 2.0.6 on 2018-06-22 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_tree_amount', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Farmer', to=settings.AUTH_USER_MODEL)),
                ('person_in_charge', models.ManyToManyField(related_name='PIC', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30)),
                ('amount', models.IntegerField(blank='True', null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg_banana', models.IntegerField()),
                ('amout_trees', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_trees', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm')),
                ('month', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='farmer.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='planting',
            name='yield_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Yield'),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Year'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='month',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='farmer.Month'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='yield_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Yield'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='month',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='farmer.Month'),
        ),
        migrations.AddField(
            model_name='farm',
            name='zone',
            field=models.ManyToManyField(to='farmer.Zone'),
        ),
    ]
