# Generated by Django 2.0.6 on 2018-06-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('PIC', models.CharField(default='', max_length=30)),
                ('phone_number', models.IntegerField(blank='True')),
                ('tree_amount', models.IntegerField()),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField()),
                ('amount', models.IntegerField(blank='True', default='2')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg_banana', models.IntegerField()),
                ('date', models.DateField(blank='True', default='20180910')),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_number', models.IntegerField()),
                ('tree_amount', models.IntegerField()),
                ('date', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer')),
            ],
        ),
        migrations.AddField(
            model_name='harvest',
            name='yield_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Yield'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='yield_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Yield'),
        ),
    ]
