# Generated by Django 2.0.6 on 2018-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='PIC',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='zone',
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='amount',
            field=models.IntegerField(blank='True'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='used',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='farmer',
            name='zone',
            field=models.ManyToManyField(to='farmer.Zone'),
        ),
    ]
