# Generated by Django 2.0.6 on 2018-06-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30)),
                ('amount', models.IntegerField(blank='True', null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm')),
                ('month', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='farmer.Month')),
            ],
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='month',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='month',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='yield_id',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='month',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='yield_id',
        ),
        migrations.AddField(
            model_name='yield',
            name='harvested_amount_kg_banana',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='planted_amount_trees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
        migrations.DeleteModel(
            name='Planting',
        ),
        migrations.AddField(
            model_name='report',
            name='yield_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Yield'),
        ),
    ]
