# Generated by Django 2.0.6 on 2018-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20180623_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='yield_id',
        ),
        migrations.AddField(
            model_name='report',
            name='yield_id',
            field=models.ManyToManyField(to='farmer.Yield'),
        ),
    ]
