# Generated by Django 2.0.6 on 2018-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20180621_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_input_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='pic',
            field=models.ManyToManyField(blank='True', to='farmer.Person_input_content'),
        ),
    ]
