# Generated by Django 2.0.6 on 2018-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20180623_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='yield_id',
            new_name='yields_id',
        ),
        migrations.RenameField(
            model_name='yield',
            old_name='harvested_amount_kg_banana',
            new_name='amount_harvested_kg_banana',
        ),
        migrations.RenameField(
            model_name='yield',
            old_name='planted_amount_trees',
            new_name='amount_planted_trees',
        ),
        migrations.AddField(
            model_name='yield',
            name='amout_harvested_trees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
