# Generated by Django 2.0.6 on 2018-06-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20180621_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yield',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
