# Generated by Django 2.0.6 on 2018-06-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20180623_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yield',
            old_name='amount_harvested_kg_banana',
            new_name='harvested_amount_kg_banana',
        ),
        migrations.RenameField(
            model_name='yield',
            old_name='amount_planted_trees',
            new_name='harvested_amout_trees',
        ),
        migrations.RenameField(
            model_name='yield',
            old_name='amout_harvested_trees',
            new_name='planted_amount_trees',
        ),
    ]
