# Generated by Django 2.0.6 on 2018-06-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20180621_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_trees', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='yield',
            name='tree_amount',
        ),
        migrations.AddField(
            model_name='planting',
            name='yield_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Yield'),
        ),
    ]
