# Generated by Django 2.0.6 on 2018-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20180621_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(default='hallo', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='planting',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
