# Generated by Django 2.0.6 on 2018-06-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20180623_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='yield',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm'),
            preserve_default=False,
        ),
    ]
