# Generated by Django 2.0.6 on 2018-06-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20180621_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('role', models.BooleanField(choices=[('farmer', 'Farmer'), ('agricultural_department', 'Agricultural department'), ('factory_owner', 'Factory owner'), ('pic', 'Person in Charge Farmer')])),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='pic',
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Person_input_content',
        ),
    ]
