# Generated by Django 2.0.6 on 2018-06-23 07:09

from django.db import migrations, models
import django.db.models.deletion
import farmer.models.formsInfo


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_yield_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Trees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_amount_trees', models.IntegerField()),
                ('harvested_amount_kg_banana', models.IntegerField()),
                ('harvested_amout_trees', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm')),
            ],
            options={
                'verbose_name': farmer.models.formsInfo.Yield,
            },
        ),
        migrations.RemoveField(
            model_name='yield',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='yield',
            name='harvested_amount_kg_banana',
        ),
        migrations.RemoveField(
            model_name='yield',
            name='harvested_amout_trees',
        ),
        migrations.RemoveField(
            model_name='yield',
            name='planted_amount_trees',
        ),
    ]
