# Generated by Django 2.0.6 on 2018-06-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20180621_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=30)),
                ('total_tree_amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='yield_id',
        ),
        migrations.RemoveField(
            model_name='yield',
            name='farmer',
        ),
        migrations.AddField(
            model_name='harvest',
            name='amout_trees',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank='True', max_length=18),
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.User'),
        ),
        migrations.AddField(
            model_name='farm',
            name='zone',
            field=models.ManyToManyField(to='farmer.Zone'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='farm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.Farm'),
            preserve_default=False,
        ),
    ]
