# Generated by Django 2.0.6 on 2018-06-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20180623_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_trees',
            name='planted_amount_trees',
            field=models.IntegerField(verbose_name='Yield'),
        ),
    ]
