# Generated by Django 2.0.6 on 2018-06-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20180621_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='farm',
            name='pic',
            field=models.ManyToManyField(related_name='PIC', to='farmer.User'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Farmer', to='farmer.User'),
        ),
    ]
