# Generated by Django 2.0.6 on 2018-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20180623_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report_trees',
            options={'verbose_name': 'Yield'},
        ),
        migrations.AlterField(
            model_name='report_trees',
            name='planted_amount_trees',
            field=models.IntegerField(),
        ),
    ]
