# Generated by Django 2.0.6 on 2018-06-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_auto_20180621_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(choices=[('farmer', 'farmer'), ('agricultural_department', 'Agricultural department'), ('factory_owner', 'Factory owner'), ('pic', 'Person in Charge Farmer')]),
        ),
    ]
