# Generated by Django 2.0.6 on 2018-06-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_auto_20180621_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'farmer'), ('agricultural_department', 'Agricultural department'), ('factory_owner', 'Factory owner'), ('pic', 'Person in Charge Farmer')], max_length=30),
        ),
    ]
