# Generated by Django 2.0.6 on 2018-06-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_auto_20180623_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report_Trees',
            new_name='Tree_data',
        ),
    ]
