# Generated by Django 2.0.6 on 2018-06-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20180623_0727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tree_data',
            new_name='Tree',
        ),
    ]
