# Generated by Django 2.0.6 on 2018-06-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20180621_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='pic',
            new_name='person_in_charge',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('agricultural_department', 'Agricultural department'), ('factory_owner', 'Factory owner'), ('pic', 'Person in Charge Farmer')], max_length=30),
        ),
    ]
