# Generated by Django 2.0.6 on 2018-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_auto_20180621_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='used',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30),
        ),
    ]
