# Generated by Django 2.0.6 on 2018-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_auto_20180621_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='amount',
            field=models.IntegerField(blank='True', null=True),
        ),
    ]
