# Generated by Django 2.0.6 on 2018-06-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_auto_20180621_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer',
            old_name='farm_id',
            new_name='farm',
        ),
    ]
