"""
Django settings for banna project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')ovq-ow=m0xv^m_6e531jc&unb5)#9x%=&v#4tu*j4!3%*a7ii'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'dashboard',
    'farmer',
    'banna',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'widget_tweaks',
    'django.contrib.staticfiles'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware'
]

ROOT_URLCONF = 'banna.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'banna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/farmer/login_redirect'
LOGOUT_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# This settings file is based on: https://github.com/abaart/KasaDaka-VSDK/blob/master/vsdk/settings.py
try:
    SFTP_PASS =  os.environ['SFTP_PASS']
    SFTP_USER = os.environ['SFTP_USER']
    HEROKU =os.environ['HEROKU']
    SFTP_HOST = os.environ['SFTP_HOST']
    SFTP_PORT = os.environ['SFTP_PORT']

except KeyError:
    # Some hardcoded variables for local testing
    SFTP_PASS = ""
    SFTP_USER = "group2"
    HEROKU = False
    SFTP_HOST = "django-static.vps.abaart.nl"
    SFTP_PORT = ""


if HEROKU:
    STATIC_URL = "http://" + SFTP_HOST + "/" + SFTP_USER + "/django/"

    DEBUG = True

    SFTP_STORAGE_HOST = SFTP_HOST
    SFTP_STORAGE_ROOT = '/django/'
    SFTP_STORAGE_PARAMS = {
        'port': SFTP_PORT,
        'username': SFTP_USER,
        'password': SFTP_PASS,
        'allow_agent': False,
        'look_for_keys': False,
        }
    STATICFILES_LOCATION = SFTP_STORAGE_HOST + '/static/'
    MEDIAFILES_LOCATION = SFTP_STORAGE_HOST + '/media/'
    DEFAULT_FILE_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
    STATICFILES_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
    MEDIA_URL = "http://" + SFTP_HOST + "/" + SFTP_USER + "/django/media/"

    DATABASES = {
        "default": dj_database_url.config()
    }
else:
    STATIC_URL = "/static/"
